# Generated by Django 5.0 on 2024-01-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='Todo',
        ),
    ]
